### PR TITLE
"name" field support for hkube-core repos

### PR DESCRIPTION
**Pull request by RonShvarz**
added name replacement if hkube-core repo has "name" field in package.json, by fetching it, while in the proccess of building version.json

part of the kube-HPC/hkube#1684 issue

- - -
This change is [Reviewable](https://reviewable.io/reviews/kube-HPC/release-manager/46)

### CODE REVIEW

**Review by golanha — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/release-manager/46)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @RonShvarz)

___
*[`scripts/getVersions.js` line 44 at r1](https://reviewable.io/reviews/kube-HPC/release-manager/46#-NTNI9zf5ZOcilRg_GMi:-NTNI9zf5ZOcilRg_GMj:b-ef3ptb) ([raw file](https://github.com/kube-HPC/release-manager/blob/3bc1f2c9cd89e321a3b13b8cef6e002d054dcf51/scripts/getVersions.js#L44)):*
> ```JavaScript
> const getRepoPackageNames = async (github,options) => {
>     let jsonMetaData = {};
>     const contents = await github.repos.getContents(options);
> ```

 const contents = await github.repos.getContents({...options, "path":"package.json"})



_Code quote:_
```JavaScript
 const contents = await github.repos.getContents(options)
```

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/release-manager/46)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`scripts/getVersions.js` line 44 at r1](https://reviewable.io/reviews/kube-HPC/release-manager/46#-NTNI9zf5ZOcilRg_GMi:-NTNawB02JuelVUVhFZK:b-e8nbat) ([raw file](https://github.com/kube-HPC/release-manager/blob/3bc1f2c9cd89e321a3b13b8cef6e002d054dcf51/scripts/getVersions.js#L44)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

 const contents = await github.repos.getContents({...options, "path":"package.json"})
</blockquote></details>

this resulted in a runtime error, i instead made the same line in a variable and then sent the variable inside.

**Review by RonShvarz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/release-manager/46)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @golanha)

___
*[`scripts/getVersions.js` line 44 at r1](https://reviewable.io/reviews/kube-HPC/release-manager/46#-NTNI9zf5ZOcilRg_GMi:-NTNawB02JuelVUVhFZK:b-e8nbat) ([raw file](https://github.com/kube-HPC/release-manager/blob/3bc1f2c9cd89e321a3b13b8cef6e002d054dcf51/scripts/getVersions.js#L44)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

 const contents = await github.repos.getContents({...options, "path":"package.json"})
</blockquote></details>

this resulted in a runtime error, i instead made the same line in a variable and then sent the variable inside.

**Review by golanha — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-HPC/release-manager/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RonShvarz)

**Pull request merged**
